### ISSUE TITLE
What difference `FROM node:4.6.2 as builder VS FROM node:4.6.2-alpine as runner`?

### ISSUE THREAD

**Issue by thearabbit** [banjerluke/meteor-dockerfile#2]
What difference `FROM node:4.6.2 as builder VS FROM node:4.6.2-alpine as runner`?
Could I use the same
```js
// Example
FROM node:4.6.2-alpine as builder
..........
FROM node:4.6.2-alpine as runner
------------- OR ----------
// Example
FROM node:4.6.2 as builder
..........
FROM node:4.6.2 as runner
```

**Comment by banjerluke** [comment]
No, it's that way for a reason. The first FROM line is for the builder image, which needs to have more "stuff" in it than the alpine image provides. But the alpine image provides everything needed to run the server, so it's used in the second image, which starts from the second FROM line, in order to result in a smaller final image. Look up "multistage Dockerfiles" to learn more. One could use the standard image in both (stripping `-alpine` from the second From line) but there's no reason to and it would result in a larger final image size.

**Comment by thearabbit** [comment]
Thanks
